import math
import csv
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.lines import Line2D

# --- Made by Aleksandr Ivanov, aleksandr.ivanov@ucdconnect.ie
# This program takes the CSV files generated by DataGenerator.java and converts them into
# graphs and a correlation coefficient table.
#
# Each CSV is read as a 2-column data object, which is turned into a line of best fit and a scatter plot.
# It is then plotted on the same graph for all CSV files for a certain sorting algorithm-scenario combination.
# The correlation coefficient is also calculated for each CSV, and the average is stored in correlation.csv.

# The file paths for the CSVs in Python are relative, hence this program shouldn't cause any issues when run.
# If something goes wrong, you may need to modify the file paths for the CSVs.


# NOTE:
# the code is heavily recycled; it is mostly the same code block, with slight modifications

# sets up a CSV file for storing the correlation coefficients
csv_file = open('correlation.csv', 'w', newline='')
csv_writer = csv.writer(csv_file, delimiter=',')
# to write a row, make a list of strings, and put it as the argument inside writerow()
csv_writer.writerow(["Sorting Algorithm", "Bubble Sort", "Counting Sort", "Merge Sort", "Quick Sort"])

# BUBBLE SORT
plt.figure(figsize=(8,5))

# Random case

# Makes an array for the sum of correlation coefficients for each CSV file
# This is so that an individual average can be calculated for each CSV file
bs_r_corr = [0,0,0,0,0,0,0,0,0,0]
# For loop, going up to 10
x = 1
while x < 11:
    # For loop, going up to 2
    i = 0
    while i < 3:
        # Reads in the CSV file
        plot = pd.read_csv('Output/BubbleSort/Random/{}/{}.csv'.format(x, i), header=None)
        # Calculates the correlation coefficient for the data in the CSV file
        bs_r_corr[x-1] += plot.corr().iloc[0,1].round(8)
        # Makes a line of best fit
        slope, intercept = np.polyfit(plot[0]**2, plot[1], 1)
        best_fit_line = slope*plot[0]**2 + intercept
        # Plots the individual data points on the graph
        plt.scatter(plot[0]**2, plot[1], marker='v',facecolors='none', edgecolors='#CD8641', linewidths=0.5)
        # Plots the line of best fit on the graph
        plt.plot(plot[0]**2, best_fit_line, color='#CD8641', alpha=0.6)
        # Moves the loop forward
        i = i + 1
    # Gets the average correlation coefficient after the second for loop
    bs_r_corr[x-1] /= 3
    # Moves the loop forward
    x = x + 1

# From now on, basically the same code is used for reading the CSV

# Worst case
bs_w_corr = 0
x = 0
while x < 20:
    plot = pd.read_csv('Output/BubbleSort/Reverse/{}.csv'.format(x), header=None)
    slope, intercept = np.polyfit(plot[0] ** 2, plot[1], 1)
    best_fit_line = slope * plot[0] ** 2 + intercept
    bs_w_corr += plot.corr().iloc[0,1].round(8)
    plt.scatter(plot[0] ** 2, plot[1], marker='s', facecolors='none', edgecolors='#CE39CE', linewidths=0.5)
    plt.plot(plot[0] ** 2, best_fit_line, color='#CE39CE', alpha=0.6)
    x = x+1
bs_w_corr /= 20

# Best case
bs_b_corr = 0
x = 0
while x < 20:
    plot = pd.read_csv('Output/BubbleSort/Sorted/{}.csv'.format(x), header=None)
    slope, intercept = np.polyfit(plot[0] ** 2, plot[1], 1)
    best_fit_line = slope * plot[0] ** 2 + intercept
    bs_b_corr += plot.corr().iloc[0,1].round(8)
    plt.scatter(plot[0] ** 2, plot[1], marker='d', facecolors='none', edgecolors='#16C4C4', linewidths=0.5)
    plt.plot(plot[0] ** 2, best_fit_line, color='#16c4c4', alpha=0.6)
    x = x + 1
bs_b_corr /= 20

# Adds gridlines with a specified transparency to the graph
plt.grid(True, alpha=0.4)
# Labels the axes of the graph
plt.xlabel('Input Size squared (n^2)')
plt.ylabel('Energy Consumption (J)')
# Puts a custom legend onto the graph - this is to avoid 30 elements in the legend for each scenario
legend_elements = [
    Line2D([0], [0], color='#CD8641', marker='v', linestyle='None', label='Random Inputs 1 - 10'),
    Line2D([0], [0], color='#CE39CE', marker='s', linestyle='None', label='Worst case Input'),
    Line2D([0], [0], color='#16C4C4', marker='d', linestyle='None', label='Best case Input')
]
plt.legend(loc='upper left',handles=legend_elements)
# Puts a title on the graph
plt.title('Bubble Sort')
# Saves the graph to a file, and shows it in the IDE
plt.savefig("Bubble Sort")
plt.show()


# From now on, the same code is used for basically everything, with slight variations

# Counting Sort

# Worst case (Big K)
cs_w_corr = 0
x = 0
while x < 20:
    plot = pd.read_csv('Output/CountingSort/Random_BigK/{}.csv'.format(x), header=None)
    slope, intercept = np.polyfit(plot[0], plot[1], 1)
    best_fit_line = slope * plot[0] + intercept
    cs_w_corr += plot.corr().iloc[0,1].round(8)
    plt.scatter(plot[0], plot[1], marker='s', facecolors='none', edgecolors='#CE39CE', linewidths=0.5)
    plt.plot(plot[0], best_fit_line, color='#CE39CE', alpha=0.4)
    x = x+1
cs_w_corr /= 20

# Best case (Small K)
cs_b_corr = 0
x = 0
while x < 20:
    plot = pd.read_csv('Output/CountingSort/Random_SmallK/{}.csv'.format(x), header=None)
    slope, intercept = np.polyfit(plot[0], plot[1], 1)
    best_fit_line = slope * plot[0]+ intercept
    cs_b_corr += plot.corr().iloc[0,1].round(8)
    plt.scatter(plot[0], plot[1], marker='d', facecolors='none', edgecolors='#16C4C4', linewidths=0.5)
    plt.plot(plot[0], best_fit_line, color='#16c4c4', alpha=0.4)
    x = x + 1
cs_b_corr /= 20

plt.grid(True, alpha=0.4)
plt.xlabel('Input Size (n)')
plt.ylabel('Energy Consumption (J)')
legend_elements = [
    Line2D([0], [0], color='#CE39CE', marker='s', linestyle='None', label='Worst Case Input'),
    Line2D([0], [0], color='#16C4C4', marker='d', linestyle='None', label='Best Case input')
]
plt.legend(loc='upper left',handles=legend_elements)
plt.title('Counting Sort')
plt.savefig("Counting Sort")
plt.show()




# Merge Sort
base = 5
plt.figure(figsize=(8,5))
ms_r_corr = [0,0,0,0,0,0,0,0,0,0]

# Random
x = 1
while x < 11:
    i = 0;
    while i < 3:
        plot = pd.read_csv('Output/MergeSort/Random/{}/{}.csv'.format(x, i), header=None)
        slope, intercept = np.polyfit(plot[0] * np.log2(plot[0]), plot[1], 1)
        best_fit_line = slope*plot[0] * np.log2(plot[0]) + intercept
        ms_r_corr[x-1] += plot.corr().iloc[0,1].round(8)
        plt.scatter(plot[0]*np.log2(plot[0]), plot[1], marker='v',facecolors='none', edgecolors='#CD8641', linewidths=0.5)
        plt.plot(plot[0]*np.log2(plot[0]), best_fit_line, color='#CD8641', alpha=0.4)

        i = i + 1
    ms_r_corr[x-1] /= 3
    x = x + 1


# Worst case (Alternating)
ms_w_corr = 0
x = 0
while x < 30:
    plot = pd.read_csv('Output/MergeSort/Alternating/{}.csv'.format(x), header=None)
    slope, intercept = np.polyfit(plot[0] * np.log2(plot[0]), plot[1], 1)
    best_fit_line = slope * plot[0] * np.log2(plot[0]) + intercept
    ms_w_corr += plot.corr().iloc[0,1].round(8)
    plt.scatter(plot[0] *np.log2(plot[0]), plot[1], marker='s', facecolors='none', edgecolors='#CE39CE', linewidths=0.5)
    plt.plot(plot[0] *np.log2(plot[0]), best_fit_line, color='#CE39CE', alpha=0.4)
    x = x+1
ms_w_corr /= 30

# Best case (Sorted)
ms_b_corr = 0
x = 0
while x < 30:
    plot = pd.read_csv('Output/MergeSort/Sorted/{}.csv'.format(x), header=None)
    slope, intercept = np.polyfit(plot[0] * np.log2(plot[0]), plot[1], 1)
    best_fit_line = slope * plot[0] * np.log2(plot[0]) + intercept
    ms_b_corr += plot.corr().iloc[0,1].round(8)
    plt.scatter(plot[0] *np.log2(plot[0]), plot[1], marker='d', facecolors='none', edgecolors='#16C4C4', linewidths=0.5)
    plt.plot(plot[0] *np.log2(plot[0]), best_fit_line, color='#16c4c4', alpha=0.4)
    x = x + 1
ms_b_corr /= 30

plt.grid(True, alpha=0.4)
plt.xlabel('n log n of Input Size')
plt.ylabel('Energy Consumption (J)')
legend_elements = [
    Line2D([0], [0], color='#CD8641', marker='v', linestyle='None', label='Random Inputs 1 - 10'),
    Line2D([0], [0], color='#CE39CE', marker='s', linestyle='None', label='Worst case Input'),
    Line2D([0], [0], color='#16C4C4', marker='d', linestyle='None', label='Best case Input')
]
plt.legend(loc='upper left',handles=legend_elements)
plt.title('Merge Sort')
plt.savefig("Merge Sort")
plt.show()


# QUICK SORT
plt.figure(figsize=(8,5))

qs_r_corr = [0,0,0,0,0,0,0,0,0,0]

# Random
x = 1
while x < 11:
    i = 0;
    while i < 3:
        plot = pd.read_csv('Output/MergeSort/Random/{}/{}.csv'.format(x, i), header=None)
        slope, intercept = np.polyfit(plot[0] * np.log2(plot[0]), plot[1], 1)
        best_fit_line = slope*plot[0] * np.log2(plot[0]) + intercept
        qs_r_corr[x-1] += plot.corr().iloc[0,1].round(8)
        plt.scatter(plot[0]*np.log2(plot[0]), plot[1], marker='v',facecolors='none', edgecolors='#CD8641', linewidths=0.5)
        plt.plot(plot[0]*np.log2(plot[0]), best_fit_line, color='#CD8641', alpha=0.4)

        i = i + 1
    qs_r_corr[x-1] /= 3
    x = x + 1

plt.xlabel('n log n of input size')
plt.ylabel('Energy Consumption (J)')
legend_elements = [
    Line2D([0], [0], color='#CD8641', marker='v', linestyle='None', label='Random Inputs 1 - 10'),
]
plt.legend(loc='upper left',handles=legend_elements)
plt.title('Quick Sort - Random Inputs')
plt.grid(True, alpha=0.4)
plt.savefig("Quick Sort - Random Inputs")
plt.show()

# Reverse-sorted (worst case)
plt.figure(figsize=(8,5))
qs_w_corr = 0
x = 0
while x < 30:
    plot = pd.read_csv('Output/QuickSort/Reverse/{}.csv'.format(x), header=None)
    slope, intercept = np.polyfit(plot[0] ** 2, plot[1], 1)
    best_fit_line = slope * plot[0] **2 + intercept
    qs_w_corr += plot.corr().iloc[0,1].round(8)
    plt.scatter(plot[0] **2 , plot[1], marker='s', facecolors='none', edgecolors='#CE39CE', linewidths=0.5)
    plt.plot(plot[0] **2, best_fit_line, color='#CE39CE', alpha=0.4)
    x = x+1
qs_w_corr /= 30


plt.xlabel('Input size squared (n^2)')
plt.ylabel('Energy Consumption (J)')
legend_elements = [
    Line2D([0], [0], color='#CE39CE', marker='s', linestyle='None', label='Worst case Input')
]
plt.legend(loc='upper left',handles=legend_elements)
plt.title('Quick Sort - Worst Case')
plt.grid(True, alpha=0.4)
plt.savefig("Quick Sort - Worst Case")
plt.show()

csv_writer.writerow(["Best Case", bs_b_corr.round(9), cs_b_corr.round(9), ms_b_corr.round(9), "-"])
csv_writer.writerow(["Worst Case", bs_w_corr.round(9), cs_w_corr.round(9), ms_w_corr.round(9), qs_w_corr.round(9)])
x = 1
while x < 11:
    csv_writer.writerow(["random_{}".format(x), bs_r_corr[x-1].round(9), "-", ms_r_corr[x-1].round(9), qs_r_corr[x-1].round(9)])
    x += 1

